### ISSUE TITLE
Failing conda-upload

### ISSUE THREAD

**Issue by jjjgoulding** [arup-group/actions-city-modelling-lab#84]
mamba-org/setup-micromamba step is failing when used on [esop-py](https://github.com/arup-group/esop-py)

```
 Error: The process '/home/azureadmin/actions-runner/_work/_temp/bin/micromamba' failed with exit code null
```

The release previously worked [here](https://github.com/arup-group/esop-py/actions/runs/14491756981/attempts/1) for v1.0.0 but failed for the release of v1.0.1 [here](https://github.com/arup-group/esop-py/actions/runs/14798218611) 

When we attempted to re-run release CD action for v1.0.0 [here](https://github.com/arup-group/esop-py/actions/runs/14491756981) the exact same error occurs. 

Possible errors:
- python version not specified - all other uses of mamba-org/setup-micromamba  in CML actions specify 3.11
- caching of install files causing failure.
- micromamba version too old '1.5.10-0'

Current workflow:

```yaml
on:
  workflow_call:
    inputs:
      package_name:
        description: "Name of Python package name being uploaded"
        required: true
        type: string
      version:
        description: "Version to be packaged and uploaded"
        required: false
        type: string
        default: ${{ github.ref_name }}
      build_workflow:
        description: "Name of workflow file used to build the package initially, if different from current workflow"
        required: false
        type: string
        default: ""
      environment:
        description: "GitHub environment in which secrets are stored"
        type: string
        default: "release"
      destination:
        description: "Upload packaging index destination. Must be one of [anaconda, internal]."
        type: string
        default: anaconda
    secrets:
      ANACONDA_TOKEN:
        required: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  conda-anaconda-publish:
    if: inputs.destination == 'anaconda'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARTIFACTNAME: "conda-build[a-zA-Z0-9-.]*-${{ inputs.package_name }}-${{ inputs.version }}"
    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v2
      with:
        micromamba-version: '1.5.10-0'
        environment-name: condaupload
        create-args: >-
            python=3.11
            anaconda-client
        post-cleanup: all
        cache-environment: True

    - name: Download built conda package from another workflow
      if: inputs.build_workflow != ''
      uses: dawidd6/action-download-artifact@v9
      with:
        name: ${{ env.ARTIFACTNAME }}
        name_is_regexp: true
        workflow: ${{ inputs.build_workflow }}
        path: ${{ runner.temp }}/conda_builds

    - name: Download built conda package from same workflow
      if: inputs.build_workflow == ''
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ env.ARTIFACTNAME }}
        path: ${{ runner.temp }}/conda_builds

    - name: Get version without the v
      run: |
        TAG=${{ inputs.version }}
        echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Upload to anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: find ${{ runner.temp }}/conda_builds -path "**/${{ inputs.package_name }}-${{ env.VERSION }}-*.tar.bz2" -exec anaconda upload {} +

  conda-internal-publish:
    if: inputs.destination == 'internal'
    runs-on: [self-hosted, linux, packages]
    env:
      ARTIFACTNAME: "conda-build[a-zA-Z0-9-.]*-${{ inputs.package_name }}-${{ inputs.version }}"
      PACKAGENAME: "conda-build-*-${{ inputs.package_name }}-${{ inputs.version }}"
    steps:
      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: '1.5.10-0'
          environment-name: condaindex
          create-args: conda-index
          post-cleanup: all
          cache-environment: true
          micromamba-binary-path: ${{ runner.temp }}/bin/micromamba

      - name: Download built conda package from another workflow
        uses: dawidd6/action-download-artifact@v9
        with:
          name: ${{ env.ARTIFACTNAME }}
          name_is_regexp: true
          workflow: ${{ inputs.build_workflow }}
          path: ${{ runner.temp }}/conda_builds

      - name: Get version without the v
        run: |
          TAG=${{ inputs.version }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      # Move to a location that can be accessed at packages.arup.com
      - name: Move package to download location
        shell: bash
        run: |
          touch ${{ runner.temp }}/.condarc
          rsync -a -v --prune-empty-dirs --include '*/' --include '${{ inputs.package_name }}-${{ env.VERSION }}-*.tar.bz2' --exclude '*' ${{ runner.temp }}/conda_builds/${{ env.PACKAGENAME }}/ ~/packages/conda/

      - name: Re-index conda
        env:
          CONDARC: ${{ runner.temp }}/.condarc
        shell: bash -l {0}
        run: python -m conda_index ~/packages/conda
```
