### ISSUE TITLE
Docs deploy action should accept an optional release name input parameter for stable docs

### ISSUE THREAD

**Issue by mfitz** [arup-group/actions-city-modelling-lab#85]
## Motivation for the new Feature
We often publish multiple versions of project documentation, where each version corresponds to a release:

<img width="292" alt="Image" src="https://github.com/user-attachments/assets/4f65ccea-f912-41ba-a257-d7355e1c84d1" />

The reusable action in `docs-deploy.yml` derives the documentation version name [from the `github.ref_name` variable](https://github.com/arup-group/actions-city-modelling-lab/blob/0057d8f145d5abbbce518a36d89e3fe0e4b0f808/.github/workflows/docs-deploy.yml#L83) when deploying "stable" docs. In caller workflows, this action is typically triggered by a release, so `github.ref_name` resolves to the release/tag name. This is exactly what I want to happen.

However, if a stable docs deploy triggered by a release fails for some reason, as happened recently in one of our private repos, the new version of the documentation is not published. What I want to do in this case is fix any underlying problem, then re-trigger the workflow to publish the stable docs under the same tag/release name.

## Implementation Idea
It is possible to add a manual trigger to a caller workflow using the Actions [`workflow_dispatch` event](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/). However, a workflow triggered in this way will resolve `github.ref_name` to the branch from which the workflow was triggered, rather than a specified release name. I want to pass an arbitrary name parameter (which will be the latest release name) when invoking the action in this way.

The action currently accepts a parameter like this ([`development_version_name`](https://github.com/arup-group/actions-city-modelling-lab/blob/0057d8f145d5abbbce518a36d89e3fe0e4b0f808/.github/workflows/docs-deploy.yml#L8)), but it is only used when publishing bleeding-edge docs, rather than stable docs for a release (see [here](https://github.com/arup-group/actions-city-modelling-lab/blob/0057d8f145d5abbbce518a36d89e3fe0e4b0f808/.github/workflows/docs-deploy.yml#L76)).

We should add a new input param to `docs-deploy.yml` (`stable_version_name` or similar), that allows us to publish stable docs under an arbitrary name, rather than `github.ref_name`. The relevant section of the workflow would then look something like:

```yaml
    - name: Deploy stable docs to gh-pages branch
      if: inputs.deploy_type == 'update_stable'
      run: |
        mike deploy --push ${{ inputs.stable_version_name || github.ref_name }}
        mike deploy --push --update-aliases ${{ inputs.stable_version_name || github.ref_name }} stable
        mike set-default --push stable
```

Caller workflows could then look something like:

```yaml
name: Publish

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to simulate (optional)'
        required: false
        type: string

jobs:
  docs-stable:
    permissions:
      contents: write
    uses: arup-group/actions-city-modelling-lab/.github/workflows/docs-deploy.yml@v1.1.0
    with:
      deploy_type: update_stable
      additional_env_create_args: "-c bioconda"
      stable_version_name: ${{ inputs.release_tag }}
 
      
```
